-- FINAL MIGRATION SCRIPT
-- 1. Add 'flags' column for auto-translation tracking
ALTER TABLE app_translations 
ADD COLUMN IF NOT EXISTS flags JSONB DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'Uncategorized';

-- 2. Seed missing translation keys
-- (Run this to populate the DB with English keys for the new UI)

-- Run this to manually insert keys if auto-discovery is slow or blocked.

INSERT INTO app_translations (key, translations) VALUES
-- Tracker / Workout
('Joined workout session!', '{}'),
('Session updated', '{}'),
('Failed to search address', '{}'),
('You already have this gym in your list!', '{}'),
('Successfully joined', '{}'),
('Failed to join gym', '{}'),
('Unknown error', '{}'),
('Successfully added', '{}'),
('Failed to save gym', '{}'),
('Joined', '{}'),
('Failed to join', '{}'),

-- Workout Summary
('LEVEL UP!', '{}'),
('WORKOUT COMPLETE!', '{}'),
('LEVEL', '{}'),
('Total XP', '{}'),
('Duration', '{}'),
('Volume', '{}'),
('CONTINUE', '{}'),

-- Workout Active
('Cancel Workout?', '{}'),
('Are you sure you want to cancel? This will discard all progress for this session.', '{}'),
('Discard Workout', '{}'),
('Remove', '{}'),
('Exercise', '{}'),
('This will remove the exercise and all its sets from the current session.', '{}'),
('STRICT', '{}'),
('Live Session', '{}'),
('Coached', '{}'),
('CANCEL', '{}'),
('FINISH', '{}'),
('Finish Workout?', '{}'),
('Are you sure you want to finish and save this session?', '{}'),
('Ghost Mode', '{}'),
('Hide from feed & leaderboards', '{}'),
('Cancel', '{}'),
('Finish', '{}'),
('KG', '{}'),
('REPS', '{}'),
('RPE', '{}'),
('Add Set', '{}'),
('Remove Set', '{}'),
('Add Exercise', '{}'),

-- GymHub
('Verified Partner', '{}'),
('Live Floor', '{}'),
('Active', '{}'),
('View All', '{}'),
('The floor is quiet... Be the first!', '{}'),
('Syncing every 5s', '{}'),
('Working out', '{}'),
('Set', '{}'),
('The floor is empty', '{}'),
('Start a workout to see yourself here!', '{}'),
('No rankings yet. Start logging workouts!', '{}'),
('This Month', '{}'),
('No upcoming events.', '{}'),
('Create Event', '{}'),
('You are going', '{}'),
('Count me in', '{}'),
('No active challenges. Check back soon!', '{}'),
('Progress', '{}'),
('Submit Result', '{}'),
('Join Challenge', '{}'),

-- Profile & Settings
('Profile updated successfully!', '{}'),
('Failed to update profile.', '{}'),
('My Profile', '{}'),
('Display Name', '{}'),
('Height (cm)', '{}'),
('Loading...', '{}'),
('Weight (kg)', '{}'),
('Prefer not to say', '{}'),
('Male', '{}'),
('Female', '{}'),
('Other', '{}'),
('Saving...', '{}'),
('Save Profile', '{}'),
('Settings', '{}'),
('Account & Security', '{}'),
('Email, Password, Data Sync & Privacy', '{}'),
('Avatar, Name, Height, Weight & Gender', '{}'),
('Training Preferences', '{}'),
('Workout Goals & Smart Suggestions', '{}'),
('Gym & Team', '{}'),
('Membership, Trainer & Staff Access', '{}'),
('Privacy & Data', '{}'),
('Ghost Mode, Visibility & Monitors', '{}'),

-- Connect
('Connect', '{}'),
('Feed', '{}'),
('Circle', '{}'),
('Chat', '{}'),

-- Saved Workouts / Routine
('Plan', '{}'),
('Library', '{}'),
('Stats', '{}'),
('Current', '{}'),
('Change', '{}'),
('Routine', '{}'),
('Unnamed Routine', '{}'),
('Start Workout', '{}'),
('No template linked', '{}'),
('DONE', '{}'),
('MISSED', '{}'),
('Day', '{}'),
('Rest Day 💤', '{}'),
('Done', '{}'),
('Log Activity', '{}'),
('Flex Schedule', '{}'),
('No fixed days. Log whatever you train today.', '{}'),
('Log Session', '{}'),
('Start a Plan', '{}'),
('Choose a schedule or create a flex plan.', '{}'),
('Workout Library', '{}'),
('Manage your templates and presets.', '{}'),
('Tap to Edit', '{}'),
('Quick Actions', '{}'),
('Create Custom Routine', '{}'),
('View Workout History', '{}'),
('Share', '{}'),
('No friends found to share with.', '{}'),
('Exercises', '{}'),

-- Routine / Plan Manager
('New Routine', '{}'),
('Select Exercises', '{}'),
('Search exercises...', '{}'),
('Custom', '{}'),
('All Muscles', '{}'),
('Done', '{}'),
('Edit Exercise', '{}'),
('New Custom Exercise', '{}'),
('Name', '{}'),
('e.g. Weighted Dips', '{}'),
('Muscle Group', '{}'),
('Save', '{}'),
('Delete Exercise?', '{}'),
('Are you sure you want to permanently delete', '{}'),
('This cannot be undone.', '{}'),
('Routine Name', '{}'),
('e.g. Chest & Triceps', '{}'),
('Visibility', '{}'),
('Public (Friends can copy)', '{}'),
('Private (Only me)', '{}'),
('Default', '{}'),
('Sets', '{}'),
('Training Goal', '{}'),
('Auto-Detect (Smart)', '{}'),
('Strength (1-5 reps)', '{}'),
('Hypertrophy (6-12 reps)', '{}'),
('Endurance (12-20 reps)', '{}'),
('Custom Range', '{}'),
('Add More Exercises', '{}'),
('Add Exercises', '{}'),
('Create Routine', '{}'),
('Edit Routine', '{}'),
('Add custom exercise...', '{}'),
('Add & Select', '{}'),
('Save Changes', '{}'),
('Remove Exercise', '{}'),
('Delete Routine?', '{}'),
('Are you sure you want to delete this routine permanently?', '{}'),
('My Workout Plans', '{}'),
('Close', '{}'),
('Create New Plan', '{}'),
('Edit', '{}'),
('Set as Active Plan', '{}'),
('No plans yet. Create one like "Push Pull Legs" or "Bro Split".', '{}'),

-- Quick Log
('Log Activity', '{}'),
('Build your session', '{}'),
('General', '{}'),
('No Specific Exercise', '{}'),
('Using', '{}'),
('Refresh Data', '{}'),
('Add', '{}'),
('Activity', '{}'),
('Session Plan', '{}'),
('Total', '{}'),
('min', '{}'),
('Notes (Optional)', '{}'),
('How was it?', '{}'),
('Save Session', '{}'),
('Please add at least one activity.', '{}'),
('Failed to log activity', '{}'),

-- Muscles & Activities
('Chest', '{}'),
('Back', '{}'),
('Legs', '{}'),
('Calves', '{}'),
('Shoulders', '{}'),
('Biceps', '{}'),
('Triceps', '{}'),
('Traps', '{}'),
('Neck', '{}'),
('Core', '{}'),
('Cardio', '{}'),
('Other', '{}'),
('Stretch', '{}'),
('Mobility', '{}'),
('Sport', '{}'),
('Walk', '{}'),
('Delete this plan?', '{}'),
('Set as Active Plan', '{}'),
('Active', '{}'),
('No plans yet. Create one like "Push Pull Legs" or "Bro Split".', '{}'),

-- Exercises
('Bench Press', '{}'),
('Incline Bench Press', '{}'),
('Decline Bench Press', '{}'),
('Dumbbell Bench Press', '{}'),
('Chest Fly', '{}'),
('Cable Fly', '{}'),
('Push Ups', '{}'),
('Dips', '{}'),
('Deadlift', '{}'),
('Pull Ups', '{}'),
('Chin Ups', '{}'),
('Lat Pulldown', '{}'),
('Barbell Row', '{}'),
('Dumbbell Row', '{}'),
('Seated Cable Row', '{}'),
('T-Bar Row', '{}'),
('Face Pulls', '{}'),
('Shoulder Press', '{}'),
('Overhead Press', '{}'),
('Arnold Press', '{}'),
('Lateral Raises', '{}'),
('Front Raises', '{}'),
('Rear Delt Fly', '{}'),
('Upright Row', '{}'),
('Bicep Curls', '{}'),
('Barbell Curl', '{}'),
('Dumbbell Curl', '{}'),
('Hammer Curl', '{}'),
('Preacher Curl', '{}'),
('Concentration Curl', '{}'),
('Triceps Pushdown', '{}'),
('Skull Crushers', '{}'),
('Overhead Triceps Extension', '{}'),
('Close Grip Bench Press', '{}'),
('Squat', '{}'),
('Front Squat', '{}'),
('Hack Squat', '{}'),
('Leg Press', '{}'),
('Lunges', '{}'),
('Bulgarian Split Squat', '{}'),
('Step Ups', '{}'),
('Leg Extension', '{}'),
('Leg Curl', '{}'),
('Romanian Deadlift', '{}'),
('Hip Thrust', '{}'),
('Calf Raises', '{}'),
('Plank', '{}'),
('Hanging Leg Raises', '{}'),
('Dragon Flags', '{}'),
('Ab Wheel Rollout', '{}'),
('Crunches', '{}'),
('Cable Crunch', '{}'),
('Russian Twists', '{}'),
('Muscle Up', '{}'),
('Handstand Push Ups', '{}'),
('Pistol Squat', '{}'),
('Human Flag', '{}'),
('Front Lever', '{}'),
('Back Lever', '{}'),
('Celso Shrugs', '{}'),
('Barbell Shrugs', '{}'),
('Farmer\'s Walk', '{}'),
('Neck Curl', '{}'),
('Reverse Hyperextensions', '{}')

ON CONFLICT (key) DO NOTHING;
